import { z } from 'zod';


export const UpdatePackageInputSchema = z.object({
  providerId: z.string().uuid().optional(),
  categoryId: z.string().uuid().optional(),
  destinationId: z.string().uuid().optional(),
  title: z.string().max(300).optional(),
  slug: z.string().max(350).optional(),
  shortDescription: z.string().max(500).optional(),
  description: z.string().optional(),
  productType: z.enum(['fixed_tour', 'flexible_tour', 'private_tour', 'group_tour', 'activity', 'day_trip', 'multi_day_package', 'guided_city_tour', 'adventure_experience', 'cruise_boat', 'transfer_service', 'transport_rental', 'accommodation_package', 'custom_trip', 'event_package', 'ticket_pass', 'travel_product', 'package_addon']).optional(),
  durationHours: z.number().int().optional(),
  durationDays: z.number().int().optional(),
  minParticipants: z.number().int().optional(),
  maxParticipants: z.number().int().optional(),
  minAge: z.number().int().optional(),
  maxAge: z.number().int().optional(),
  difficultyLevel: z.enum(['easy', 'moderate', 'challenging', 'extreme']).optional(),
  confirmationType: z.enum(['instant', 'request_to_book']).optional(),
  cancellationPolicy: z.enum(['flexible', 'moderate', 'strict', 'non_refundable']).optional(),
  cancellationPolicyDetails: z.string().optional(),
  refundPolicy: z.string().optional(),
  terms: z.string().optional(),
  basePrice: z.string().regex(/^\d+(\.\d+)?$/).optional(),
  currency: z.string().max(3).optional(),
  featuredImage: z.string().max(500).optional(),
  gallery: z.record(z.string(), z.unknown()).optional(),
  videoUrl: z.string().max(500).optional(),
  brochureUrl: z.string().max(500).optional(),
  meetingPoint: z.string().optional(),
  meetingLatitude: z.string().regex(/^\d+(\.\d+)?$/).optional(),
  meetingLongitude: z.string().regex(/^\d+(\.\d+)?$/).optional(),
  departureLocation: z.string().max(400).optional(),
  returnLocation: z.string().max(400).optional(),
  inclusions: z.record(z.string(), z.unknown()).optional(),
  exclusions: z.record(z.string(), z.unknown()).optional(),
  amenities: z.record(z.string(), z.unknown()).optional(),
  languages: z.record(z.string(), z.unknown()).optional(),
  accessibilityInfo: z.string().optional(),
  physicalRequirements: z.string().optional(),
  tags: z.record(z.string(), z.unknown()).optional(),
  searchKeywords: z.string().optional(),
  isFeatured: z.boolean().optional(),
  rating: z.string().regex(/^\d+(\.\d+)?$/).optional(),
  reviewCount: z.number().int().optional(),
  totalBookings: z.number().int().optional(),
  status: z.enum(['draft', 'submitted', 'approved', 'published', 'unpublished', 'rejected', 'archived', 'suspended', 'expired']).optional(),
  rejectionReason: z.string().optional(),
  moderationNotes: z.string().optional(),
  metaTitle: z.string().max(200).optional(),
  metaDescription: z.string().max(500).optional(),
  deletedAt: z.string().datetime().optional(),

}).refine(data => Object.keys(data).length > 0, {
  message: 'At least one field must be provided for update',
});



export type UpdatePackageInput = z.infer<typeof UpdatePackageInputSchema>;
