import { Component } from '@angular/core'
import { CommonModule } from '@angular/common'
import { NgIcon, provideIcons } from '@ng-icons/core'
import {
  lucideTrendingUp,
  lucideUsers,
  lucideMousePointerClick,
  lucideMapPin,
  lucideStar,
  lucideCalendarCheck,
  lucideGlobe,
  lucideCompass,
} from '@ng-icons/lucide'
import { HlmCardImports } from '../../../ui/card/hlm-card.directives'
import { HlmBadgeImports } from '../../../ui/badge/hlm-badge.directive'

@Component({
  selector: 'app-travel-analytics',
  standalone: true,
  imports: [CommonModule, NgIcon, ...HlmCardImports, ...HlmBadgeImports],
  providers: [
    provideIcons({
      lucideTrendingUp,
      lucideUsers,
      lucideMousePointerClick,
      lucideMapPin,
      lucideStar,
      lucideCalendarCheck,
      lucideGlobe,
      lucideCompass,
    }),
  ],
  template: `
    <div class="space-y-6">
      <!-- 4 Marketplace Performance KPIs -->
      <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <div hlmCard class="hover:border-primary/40 transition-colors">
          <div hlmCardHeader class="flex flex-row items-center justify-between pb-2">
            <span hlmCardTitle class="text-sm font-medium">Search to Booking Conv.</span>
            <ng-icon name="lucideMousePointerClick" class="size-4 text-primary" />
          </div>
          <div hlmCardContent>
            <div class="text-2xl font-bold">3.82%</div>
            <p class="text-xs text-emerald-600 dark:text-emerald-400 font-semibold mt-1">+0.42% vs last month</p>
          </div>
        </div>

        <div hlmCard class="hover:border-primary/40 transition-colors">
          <div hlmCardHeader class="flex flex-row items-center justify-between pb-2">
            <span hlmCardTitle class="text-sm font-medium">Avg Review Score</span>
            <ng-icon name="lucideStar" class="size-4 text-amber-500 fill-amber-500" />
          </div>
          <div hlmCardContent>
            <div class="text-2xl font-bold">4.88 / 5.0</div>
            <p class="text-xs text-muted-foreground mt-1">Based on 2,410 verified reviews</p>
          </div>
        </div>

        <div hlmCard class="hover:border-primary/40 transition-colors">
          <div hlmCardHeader class="flex flex-row items-center justify-between pb-2">
            <span hlmCardTitle class="text-sm font-medium">Repeat Travelers</span>
            <ng-icon name="lucideUsers" class="size-4 text-emerald-500" />
          </div>
          <div hlmCardContent>
            <div class="text-2xl font-bold">28.4%</div>
            <p class="text-xs text-emerald-600 dark:text-emerald-400 font-semibold mt-1">+3.2% loyalty retention</p>
          </div>
        </div>

        <div hlmCard class="hover:border-primary/40 transition-colors">
          <div hlmCardHeader class="flex flex-row items-center justify-between pb-2">
            <span hlmCardTitle class="text-sm font-medium">Active Tour Guides</span>
            <ng-icon name="lucideGlobe" class="size-4 text-sky-500" />
          </div>
          <div hlmCardContent>
            <div class="text-2xl font-bold">86 Guides</div>
            <p class="text-xs text-muted-foreground mt-1">Across 14 global destinations</p>
          </div>
        </div>
      </div>

      <!-- Destination Share & Experience Distribution -->
      <div class="grid gap-4 md:grid-cols-2">
        <!-- Destinations Breakdown -->
        <div hlmCard class="p-5">
          <h3 class="text-base font-semibold text-foreground mb-1">Top Destination Share</h3>
          <p class="text-xs text-muted-foreground mb-4">Volume of bookings generated by region</p>

          <div class="space-y-3.5">
            @for (dest of destinations; track dest.name) {
              <div class="space-y-1.5">
                <div class="flex items-center justify-between text-xs">
                  <span class="font-medium text-foreground flex items-center gap-1.5">
                    <ng-icon name="lucideMapPin" class="size-3.5 text-primary" />
                    {{ dest.name }}
                  </span>
                  <span class="font-semibold text-muted-foreground tabular-nums">{{ dest.share }}% ({{ dest.bookings }} trips)</span>
                </div>
                <div class="h-2 w-full bg-muted/40 rounded-full overflow-hidden">
                  <div class="h-full bg-primary rounded-full" [style.width.%]="dest.share"></div>
                </div>
              </div>
            }
          </div>
        </div>

        <!-- Experience Categories -->
        <div hlmCard class="p-5">
          <h3 class="text-base font-semibold text-foreground mb-1">Product Category Velocity</h3>
          <p class="text-xs text-muted-foreground mb-4">Marketplace demand distribution across tour types</p>

          <div class="space-y-3.5">
            @for (cat of categories; track cat.name) {
              <div class="space-y-1.5">
                <div class="flex items-center justify-between text-xs">
                  <span class="font-medium text-foreground flex items-center gap-1.5">
                    <span class="size-2 rounded-full" [class]="cat.color"></span>
                    {{ cat.name }}
                  </span>
                  <span class="font-semibold text-muted-foreground tabular-nums">{{ cat.revenue }}</span>
                </div>
                <div class="h-2 w-full bg-muted/40 rounded-full overflow-hidden">
                  <div class="h-full rounded-full" [class]="cat.barColor" [style.width.%]="cat.percentage"></div>
                </div>
              </div>
            }
          </div>
        </div>
      </div>
    </div>
  `,
})
export class TravelAnalyticsComponent {
  readonly destinations = [
    { name: 'Swiss Alps & Interlaken', share: 34, bookings: 662 },
    { name: 'Bali & Nusa Islands', share: 26, bookings: 506 },
    { name: 'Kyoto & Tokyo Heritage', share: 18, bookings: 350 },
    { name: 'Serengeti & Ngorongoro', share: 14, bookings: 272 },
    { name: 'Santorini & Cyclades', share: 8, bookings: 158 },
  ]

  readonly categories = [
    { name: 'Multi-Day Trekking & Alpine', percentage: 42, revenue: '$202,800', color: 'bg-primary', barColor: 'bg-primary' },
    { name: 'Cultural & Sacred Heritage', percentage: 28, revenue: '$135,200', color: 'bg-emerald-500', barColor: 'bg-emerald-500' },
    { name: 'Wildlife & Safari Expeditions', percentage: 18, revenue: '$86,900', color: 'bg-amber-500', barColor: 'bg-amber-500' },
    { name: 'Cruise & Sailing Day Trips', percentage: 12, revenue: '$58,050', color: 'bg-sky-400', barColor: 'bg-sky-400' },
  ]
}
