import type { VehicleItem } from './vehicles.model';

export const MOCK_VEHICLES: VehicleItem[] = [
  {
    id: 'veh-001',
    slug: 'range-rover-autobiography-p530',
    make: 'Land Rover',
    model: 'Range Rover Autobiography P530',
    year: 2025,
    category: 'Luxury SUV',
    acrissCode: 'XFAR',
    seats: 5,
    luggageCount: 4,
    transmission: 'Automatic',
    fuelType: 'Hybrid',
    featuredImage: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?q=80&w=1200&auto=format&fit=crop',
    dailyRate: 420,
    currency: 'USD',
    unlimitedMileage: true,
    providerName: 'Apex VIP Fleet Switzerland',
    cityLocation: 'Zurich / Geneva',
    rating: 4.98,
    reviewsCount: 76,
    protectionTierIncluded: 'Zero Excess Comprehensive',
    chauffeurAvailable: true
  },
  {
    id: 'veh-002',
    slug: 'porsche-taycan-4s-cross-turismo',
    make: 'Porsche',
    model: 'Taycan 4S Cross Turismo',
    year: 2025,
    category: 'Electric Sedan',
    acrissCode: 'WDAR',
    seats: 4,
    luggageCount: 3,
    transmission: 'Automatic',
    fuelType: 'Electric',
    featuredImage: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?q=80&w=1200&auto=format&fit=crop',
    dailyRate: 380,
    currency: 'USD',
    unlimitedMileage: false,
    providerName: 'Alpine e-Drive Mobility',
    cityLocation: 'Interlaken / Milan',
    rating: 4.95,
    reviewsCount: 52,
    protectionTierIncluded: 'Standard CDW',
    chauffeurAvailable: false
  },
  {
    id: 'veh-003',
    slug: 'mercedes-benz-v-class-extra-long',
    make: 'Mercedes-Benz',
    model: 'V-Class Exclusive (Extra-Long)',
    year: 2024,
    category: 'Executive Van',
    acrissCode: 'FVAR',
    seats: 7,
    luggageCount: 7,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    featuredImage: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?q=80&w=1200&auto=format&fit=crop',
    dailyRate: 310,
    currency: 'USD',
    unlimitedMileage: true,
    providerName: 'Chauffeured Alps & Kyoto',
    cityLocation: 'Kyoto / Tokyo',
    rating: 4.96,
    reviewsCount: 110,
    protectionTierIncluded: 'Zero Excess Comprehensive',
    chauffeurAvailable: true
  }
];
